CREATE TABLE Users (
 UserId INT IDENTITY(1,1) PRIMARY KEY,
 TenDangNhap NVARCHAR(20) NOT NULL UNIQUE,
 MatKhauBam NVARCHAR(64) NOT NULL,
 Salt NVARCHAR(32) NOT NULL,
 HoTen NVARCHAR(50) NOT NULL,
 Email NVARCHAR(100) NULL,
 NgayTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 LanDangNhapCuoi DATETIME2 NULL
);
CREATE DATABASE QUANLYBANHANG1;
SELECT*FROM Users